// Generated by CoffeeScript 1.6.3
(function() {
  var Commands;

  global.chrome = {
    i18n: {
      getMessage: function() {}
    }
  };

  require("./test_helper.js");

  Commands = require("../../background_scripts/commands.js").Commands;

  context("Key mappings", should("lowercase keys correctly", function() {
    assert.equal(Commands.normalizeKey('<c-a>'), '<c-a>');
    assert.equal(Commands.normalizeKey('<C-a>'), '<c-a>');
    assert.equal(Commands.normalizeKey('<C-A>'), '<c-A>');
    assert.equal(Commands.normalizeKey('<F12>'), '<f12>');
    return assert.equal(Commands.normalizeKey('<C-F12>'), '<c-f12>');
  }));

}).call(this);
