#!/usr/bin/env coffee

fs = require "fs"
engines = require("../../background_scripts/completion_engines.js").CompletionEngines

entries =
  for engine in engines[0...engines.length-1]
    engine = new engine
    lines = []
    lines.push "###### #{engine.constructor.name}\n"
    if engine.regexps
      lines.push (engine.regexps.map (re) -> "    #{re.toString().replace(/^\//, '').replace /\/$/, ''}")...
    lines.join "\n"

header = """
  #### Completion Engines

  Search completion is supported for the following custom search engines.  If the search URL of a custom
  search engine matches one of these regular expressions, then completion suggestions will be provided in the
  vomnibar.  Completions are not provided for searches with the default search engine.

  (*Warning. This file is automatically generated.  Any changes will be overwritten.*)
"""

content = header + "\n\n" + entries.join("\n\n") + "\n"
filename = "completion_engines.md"

fs.writeFile filename, content, (error) ->
  if error
    console.log "error: failed to write #{filename}."
    process.exit 1

