#!/bin/sh

echo "Preparing to run tests..."

TDIR=`mktemp -d -t vimium`

if [ $? -ne 0 ]
then
  exit 1
fi

git checkout-index --prefix=$TDIR/ -af

pushd $TDIR > /dev/null
  cake build && cake test
  TEST_RESULT=$?
popd > /dev/null

echo "Tests completed."

rm -rf $TDIR

exit $TEST_RESULT
